---
galaxy_info:
  author: Automation Iberia
  description: AAP Configuration as Code Implementation
  company: Automation Iberia
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags: []

collections:
  - ctrliq.ascender

dependencies:
  - role: meta_dependency_check
...
