---
galaxy_info:
  role_name: settings
  author: Red Hat CoP
  description: A role to set some Ansible Controller settings
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - controller
    - aap
    - awx
    - configuration
    - setting
    - settings

collections:
  - ctrliq.ascender

dependencies:
  - role: meta_dependency_check
...
