---
authors:
  - Ascender Project Contributors
dependencies: {}
description: Ansible content that interacts with the Ascender (AWX) API
documentation: https://github.com/ctrliq/ascender-collection/blob/main/README.md
homepage: https://ascender-automation.org
issues: https://github.com/ctrliq/ascender-collection/issues
license:
  - GPL-3.0-or-later
name: ascender
namespace: ctrliq
readme: README.md
repository: https://github.com/ctrliq/ascender-collection
tags:
  - cloud
  - infrastructure
  - ascender
  - ansible
  - automation
version: 25.4.0
build_ignore:
  - tools
  - test
  - tests
  - setup.cfg
  - galaxy.yml.j2
  - template_galaxy.yml
  - '*.tar.gz'
  - .github
  - .gitignore
  - TESTING.md
  - images
