---
galaxy_info:
  role_name: jobs_cancel
  author: Sean Sullivan
  description: An Ansible Role to cancel jobs in Ansible Controller.
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - controller
    - aap
    - awx
    - workflow
    - workflows

collections:
  - ctrliq.ascender

dependencies:
  - role: meta_dependency_check
...
