---
galaxy_info:
  role_name: bulk_host_create
  author: Sean Sullivan
  description: An Ansible Role to create hosts in bulk  in Ansible Controller.
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - controller
    - aap
    - awx
    - host
    - hosts

collections:
  - ctrliq.ascender

dependencies:
  - role: meta_dependency_check
...
