---
galaxy_info:
  role_name: global_vars
  author: Ivan Aragonés
  description: Global variables to be consumed by any other role in the collection
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags: []

collections:
  - ctrliq.ascender

dependencies: []
...
