---
galaxy_info:
  author: Ivan Aragonés
  description: Global variables to be consumed by any other role in the collection
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  galaxy_tags: []

dependencies: []
...
