---
galaxy_info:
  role_name: meta_dependency_check
  author: Tom page
  description: An Ansible Role to check collection dependencies.
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags: []

collections:
  - ctrliq.ascender

dependencies: []
...
