---
galaxy_info:
  role_name: dispatch
  author: Tom Page
  description: An Ansible Role which launches all of the roles within the controller_configuration Collection.
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - controller
    - aap
    - awx
    - configuration
    - dispatch

collections:
  - ctrliq.ascender

dependencies: []
...
