---
galaxy_info:
  role_name: applications
  author: Mike Shriver
  description: An Ansible Role to create applications in Ansible Controller.
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - controller
    - aap
    - awx
    - configuration
    - application
    - applications

collections:
  - ctrliq.ascender

dependencies:
  - role: global_vars
  - role: meta_dependency_check
...
