---
galaxy_info:
  role_name: job_launch
  author: Sean Sullivan
  description: An Ansible Role to launch job templates in Ansible Controller.
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - controller
    - aap
    - awx
    - job
    - jobs

collections:
  - ctrliq.ascender

dependencies:
  - role: meta_dependency_check
...
